#!/bin/bash
#echo "Content-type: text/html"
echo ""
echo "<html>"
echo "<head><title>Bash script Test</title></head>"
echo "<body>"
echo "<h2>Bash script Test</h2>"
echo "<p>This is running from a CGI script!</p>"
echo "<p>Server time: $(date)</p>"
echo "<p>Output:</p>"
echo "<pre>"
echo "Hello world! I am $USER."
echo "</pre>"
echo "</body></html>"